openapi: 3.0.0
info:
  title: NASA Explorer API
  description: API for interacting with NASA data
  version: 1.0.0
servers:
  - url: /
components:
  parameters:
    startDate:
      in: query
      name: startDate
      schema:
        type: string
        format: date
    endDate:
      in: query
      name: endDate
      schema:
        type: string
        format: date
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          
    ValidationError:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
        
    ValidationErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            query:
              type: array
              items:
                $ref: '#/components/schemas/ValidationError'

    Picture:
      type: object
      properties:
        large:
          type: string
        small:
          type: string

    NearEarthObject:
      type: object
      properties:
        id:
          type: string
        neo_reference_id:
          type: string
        name:
          type: string
        nasa_jpl_url:
          type: string
          format: uri
        absolute_magnitude_h:
          type: number
          format: float
        estimated_diameter:
          type: object
          properties:
            kilometers:
              $ref: '#/components/schemas/DiameterRange'
            meters:
              $ref: '#/components/schemas/DiameterRange'
            miles:
              $ref: '#/components/schemas/DiameterRange'
            feet:
              $ref: '#/components/schemas/DiameterRange'
        is_potentially_hazardous_asteroid:
          type: boolean
        close_approach_data:
          type: array
          items:
            $ref: '#/components/schemas/CloseApproachData'
        is_sentry_object:
          type: boolean

    NearEarthObjectWithOrbital:
      allOf:
        - $ref: '#/components/schemas/NearEarthObject'
        - type: object
          properties:
            orbital_data:
              $ref: '#/components/schemas/OrbitalData'


    DiameterRange:
      type: object
      properties:
        estimated_diameter_min:
          type: number
          format: float
        estimated_diameter_max:
          type: number
          format: float

    CloseApproachData:
      type: object
      properties:
        close_approach_date:
          type: string
          format: date
        close_approach_date_full:
          type: string
        epoch_date_close_approach:
          type: integer
        relative_velocity:
          type: object
          properties:
            kilometers_per_second:
              type: string
            kilometers_per_hour:
              type: string
            miles_per_hour:
              type: string
        miss_distance:
          type: object
          properties:
            astronomical:
              type: string
            lunar:
              type: string
            kilometers:
              type: string
            miles:
              type: string
        orbiting_body:
          type: string

    OrbitalData:
      type: object
      properties:
        orbit_id:
          type: string
        orbit_determination_date:
          type: string
          format: date-time
        first_observation_date:
          type: string
          format: date
        last_observation_date:
          type: string
          format: date
        data_arc_in_days:
          type: integer
        observations_used:
          type: integer
        orbit_uncertainty:
          type: string
        minimum_orbit_intersection:
          type: string
        jupiter_tisserand_invariant:
          type: string
        epoch_osculation:
          type: string
        eccentricity:
          type: string
        semi_major_axis:
          type: string
        inclination:
          type: string
        ascending_node_longitude:
          type: string
        orbital_period:
          type: string
        perihelion_distance:
          type: string
        perihelion_argument:
          type: string
        aphelion_distance:
          type: string
        perihelion_time:
          type: string
        mean_anomaly:
          type: string
        mean_motion:
          type: string
        equinox:
          type: string
        orbit_class:
          type: object
          properties:
            orbit_class_type:
              type: string
            orbit_class_description:
              type: string
            orbit_class_range:
              type: string